//arrays of objects grouped by type- going to use ng-repeat to display items in list format 

var questions = {};

questions.basic = [{Q: 'Tell me about yourself.', A: 'I am a person who is super passoniate about coding and techology.  I am tenacious, a team player and a quick study. I enjoy solving intresting problems and making things so coding has been a fun adventure'},{Q: 'How did you get into coding?', A: ''}, {Q: 'What are your weaknesses', A:'One of the things I have struggled with in the past is my tendency to hyper-focus on whatever project I am working on.  In the past I have been so focused on the work in front of me, that I loose my sense of time and my surroundings.  However in the past year I have been able to become much more aware of when I am hyper focusing and able to still concentrate intently on my work while making a point to be aware of my surroundings. '},{Q: 'What did you study in school and  why?', A:''},{Q: 'What is your ideal company?', A:''}, {Q: 'What is your proudest achivement to date?', A:''}, {Q: 'Why should we hire you?', A:''}, {Q: 'What would be your ideal working environment? ', A:''}, {Q: 'If you had to choose one, would you consider yourself a big-picture person or a detail-oriented person?  ', A:''}, {Q: 'What three character traits would your friends and coworkers use to describe you? ', A:''}, {Q: 'What do you think are the qualities of a good leader? A bad leader?  ', A:''}];

questions.behavioral =[{Q: 'Tell me about a time when you had to make a quick decision.', A:''}, {Q: "Tell me a time when you had to challenge someone's idea. What was the reaction, who did you challenge?", A:''}, {Q: 'Tell me about a time when you have helped someone or corrected someone who was doing the wrong thing.', A:''}, {Q: 'Tell me about a time when you were a leader.', A: 'In my time as a Resident Assistant one of my main duties was to create a safe and welcoming environment for students.  I would occasionally have to educate people on diversity topics to understand why actions could be hurtful to other students. For example one time some students stole a teddy bear from one student and hung it in a noose in the door way.  I  had a conversation with those students about racial history and lynching in order to educate them, after that they students apologized sincerely to the students and became better hallmates.  I also mediated roommate conflicts when needed and referred residents to campus resources when needed.   Due to this experience I am confident in my ability to work in teams,  help support a diverse environment and able to help team mates work through conflicts. '}, {Q: 'Describe a time you took a risk to achieve a goal.', A:''}, {Q: 'Describe a situation where you have been particularly persistent.', A:''}, {Q: 'How well do you handle stress?', A:''}];

questions.carrer = [{Q: 'What are your future career goals?', A:''}, {Q: 'How do you want to improve yourself in the next year?', A:''}, {Q: '', A:''}, {Q: '', A:''}];
 
questions.technical = [{Q: 'Whats your preferre IDE and Why?', A:''}, {Q: 'What do you when you get stuck on a problem?', A:''}];

questions.fun = [{Q: 'How do you like your coffee?', A:''}, {Q: 'What is the last book you read?  ', A:''}, {Q: 'What is the best movie you have seen in the last year?', A:''}, {Q: 'What would you do if you won the lottery? ', A:''}, {Q: '', A:''}, {Q: '', A:''}, {Q: '', A:''}];

//{Q: '', A:''}
