//arrays of objects grouped by type- going to use ng-repeat to display items in list format 

var questions = {};

questions.basic = [{Q: 'Tell me about yourself.', A: 'I am a person who is super passoniate about coding and techology.  I am tenacious, a team player and a quick study. I enjoy solving intresting problems and making things so coding has been a fun adventure'},{Q: 'How did you get into coding?', A: ''}, {Q: 'What are your weaknesses', A:'One of the things I have struggled with in the past is my tendency to hyper-focus on whatever project I am working on.  In the past I have been so focused on the work in front of me, that I loose my sense of time and my surroundings.  However in the past year I have been able to become much more aware of when I am hyper focusing and able to still concentrate intently on my work while making a point to be aware of my surroundings. '},{Q: 'What did you study in school and  why?', A:'I studied history and biology in college. I love understanding how things works and why things  things are they way they are. Both Biology and History approach this question from different angles to complete the picture.'},{Q: 'What is your ideal company?', A:''}, {Q: 'What is your proudest achivement to date?', A:''}, {Q: 'Why should we hire you?', A:''}, {Q: 'What would be your ideal working environment? ', A:'I am a fan of the Agile methodology.    An ideal work environment would use the Agile methodology or a similar method.  I would prefer daily stand-ups followed by work time where I can find a quiet space to focus on the task in front of me for a few hours.'}, {Q: 'If you had to choose one, would you consider yourself a big-picture person or a detail-oriented person?  ', A:'I would say in general I am a more of a big picture person but I think it is important to be able to see both.'}, {Q: 'What three character traits would your coworkers use to describe you? ', A:'My coworkers would describe me as intelligent, passionate and tenacious.  They have been me be persistent with and solve tough problems at work.  I am one of the go-to people in my office, when someone has a question or problem  they will come to me even is not directly related to my position. I always do my best to help my co-workers in this situation and most of the time I am able to find a solution, or answer their question. In the rare case I cannot provide them with the correct information, after researching the issue, I send them off to someone who is able to help.  '}, {Q: 'What do you think are the qualities of a good leader? A bad leader?  ', A:'To me a good leader is someone who puts their team first rather than themselves.   A good leader should communicate clearly with their team, anticipate the needs and challenges of their team, and advocate on for their team.  Good senses of fun and humor are good bonuses.'}];

questions.behavioral =[{Q: 'Tell me about a time when you had to make a quick decision.', A:''}, {Q: "Tell me a time when you had to challenge someone's idea. What was the reaction, who did you challenge?", A:''}, {Q: 'Tell me about a time when you have helped someone or corrected someone who was doing the wrong thing.', A:''}, {Q: 'Tell me about a time when you were a leader.', A: 'In my time as a Resident Assistant one of my main duties was to create a safe and welcoming environment for students.  I would occasionally have to educate people on diversity topics to understand why actions could be hurtful to other students. For example one time some students stole a teddy bear from one student and hung it in a noose in the door way.  I  had a conversation with those students about racial history and lynching in order to educate them, after that they students apologized sincerely to the students and became better hallmates.  I also mediated roommate conflicts when needed and referred residents to campus resources when needed.   Due to this experience I am confident in my ability to work in teams,  help support a diverse environment and able to help team mates work through conflicts. '}, {Q: 'Describe a time you took a risk to achieve a goal.', A:''}, {Q: 'Describe a situation where you have been particularly persistent.', A:''}, {Q: 'How well do you handle stress?', A:'I currently work in a very high stress environment (turn over rate of 1/person a week- been there 4 years) so I am used to dealing with stress. I run to keep sane.'}];

questions.carrer = [{Q: 'What are your future career goals?', A:'In the near future I would like to learn more backed skills and move into fullstack development. I think its useful as a coder to understand both the front and back ends of an application to be able to see the big picture and communicate with your team.   Speaking more long term I would like to expand my skills include software development and to this I plan on learning C++ after learning python.  I am passionate about education eventually I want to make educational games.'}, {Q: 'How do you want to improve yourself in the next year?', A:'One of the many things I love about this field is that it critical to never stop learning.   I am currently working on learning Python and would like to have a solid fountain in it in the next year.  I also plan on getting more acquainted with several libraries and frameworks including: NodeJS, Angular2, D3, React, and Django.  Last but not least I plan to start to contribute to open source projects on  github.' }];
 
questions.technical = [{Q: 'What is your preferred IDE and Why?', A:''}, {Q: 'What do you when you get stuck on a problem?', A:''}];

questions.fun = [{Q: 'How do you like your coffee?', A:'Strong and with cream. It is Portland so of course I am a bit of a coffee snob and prefer it fresh. '}, {Q: 'What is the last book you read?  ', A:'I recently finished The Hitch Hikers Guide to the Galaxy.  I am currently working on The Restaurant at the End of The Universe and You Dont Know JS. '}, {Q: 'What is the best movie you have seen in the last year?', A:'  I really enjoyed Star Wars The Force Awakens.  I saw saw Star Wars for the first time when I was six years old and I have been a fan ever since.  The Force Awakens passes the Bechdel Test which is awesome.'}, {Q: 'What would you do if you won the lottery? ', A:'I would be surprised since I do not play the the lottery, but I would pay off my student loans, invest most of it, quit my current adminstrative job to devote myself to coding full time, and  take a trip. '}, {Q: 'Flight or Invisbilty', A: 'Invisbilty'}];

//{Q: '', A:''}